### ISSUE TITLE
More entropy, include dates and nonce in token

### ISSUE THREAD

**Issue by florianschmitt** [technical-rex/spring-security-jwt#2]
Hi, I really liked you tutorial and example project. 
One thing bugged me though. Please add more data to the Jwts, so that it does not generate the same token for the same user every time. I know its an example, but maybe someone is incautious and isn't aware of the problem.

I propose something like this:

```
    public String createTokenForUser(User user)
    {
        long validityInMillis = TimeUnit.HOURS.toMillis(1l);
        Date expiry = new Date(new Date().getTime() + validityInMillis);
        String username = user.getUsername();
        String result = Jwts.builder()//
                .setId(UUID.randomUUID().toString())//
                .setSubject(username)//
                .setExpiration(expiry)//
                .setIssuedAt(new Date())//
                .signWith(SignatureAlgorithm.HS512, secret)//
                .compact();
        return result;
    }
```

One more thing, the secret is supposed to be given as a base64-encoded String, 

```
String secret = "tooManySecrets";
String base64Secret = Base64.getEncoder().encodeToString(secret.getBytes());
tokenAuthenticationService = new TokenAuthenticationService("tooManySecrets", userService);
```

Thanks again for the nice project.

**Comment by egillespie** [comment]
Great suggestions! Given the amount of traffic I've seen on this tutorial, I'll definitely put these in.

**Comment by florianschmitt** [comment]
Cool, I can also prepare a pull request if you like.

**Comment by egillespie** [comment]
Go for it! I should be able to get around to the code change next week. And regardless of who makes the change, I'll write an amendment to the tutorial or a follow-up article to explain the changes.

**Comment by egillespie** [comment]
Hi @florianschmitt, I incorporated your suggestions and they worked like a charm. Thanks for pointing out the Base64 encoding bug on the secret. Tokens generated in this tutorial can now be inspected [jwt.io](https://jwt.io/)!

**Comment by egillespie** [comment]
Here's a [follow-up article](http://technicalrex.com/spring-security-jwt-followup) explaining the changes.
